language: go
go:
    - 1.8.x
    - 1.9.x
    - 1.10.x
install:
    - go get -v .
    - go get -v github.com/golang/lint/golint
script:
    - go build -v ./...
    - go vet ./...
    - golint -set_exit_status ./...
    - diff <(gofmt -d .) <(echo -n)
